import { Genres } from "@/generated/graphql";
import {
  Music,
  Disc3,
  Headphones,
  Radio,
  MapPin,
  Coffee,
  Repeat,
  Heart,
  Guitar,
  Zap,
  TrendingUp,
  Calendar,
  Disc,
  Star,
  Drum,
  Mic,
  Film,
  Smile,
  Speaker,
  Award,
  Landmark,
  User,
  Cloud,
} from "lucide-react";

export const allGenres = [
  { value: Genres.Disco, label: "Disco", icon: Disc3 },
  { value: Genres.Eighties, label: "80s", icon: Radio },
  { value: Genres.Nineties, label: "90s", icon: Calendar },
  { value: Genres.TwoThousands, label: "2000s", icon: Calendar },
  { value: Genres.Top_40, label: "Top 40", icon: TrendingUp },
  { value: Genres.Rnb, label: "R&B", icon: Heart },
  { value: Genres.HipHop, label: "Hip Hop", icon: Headphones },
  { value: Genres.Rap, label: "Rap", icon: Mic },
  { value: Genres.Reggae, label: "Reggae", icon: Music },
  { value: Genres.Reggaeton, label: "Reggaeton", icon: Music },
  { value: Genres.Rock, label: "Rock", icon: Guitar },
  { value: Genres.AlternativeRock, label: "Alt Rock", icon: Guitar },
  { value: Genres.Metal, label: "Metal", icon: Drum },
  { value: Genres.Jazz, label: "Jazz", icon: Music },
  { value: Genres.Blues, label: "Blues", icon: Music },
  { value: Genres.Funk, label: "Funk", icon: Music },
  { value: Genres.Country, label: "Country", icon: Music },
  { value: Genres.Folk, label: "Folk", icon: Landmark },
  { value: Genres.Pop, label: "Pop", icon: Star },
  { value: Genres.Techno, label: "Techno", icon: Zap },
  { value: Genres.House, label: "House", icon: Music },
  { value: Genres.DeepHouse, label: "Deep House", icon: Cloud },
  { value: Genres.Trance, label: "Trance", icon: Disc },
  { value: Genres.Edm, label: "EDM", icon: Disc },
  { value: Genres.Dubstep, label: "Dubstep", icon: Drum },
  { value: Genres.DrumAndBass, label: "Drum & Bass", icon: Drum },
  { value: Genres.Trap, label: "Trap", icon: Drum },
  { value: Genres.Ambient, label: "Ambient", icon: Cloud },
  { value: Genres.Lounge, label: "Lounge", icon: Coffee },
  { value: Genres.Vinyl, label: "Vinyl", icon: Disc },
  { value: Genres.Remixes, label: "Remixes", icon: Repeat },
  { value: Genres.Bollywood, label: "Bollywood", icon: Award },
  { value: Genres.Punjabi, label: "Punjabi", icon: User },
  { value: Genres.Tamil, label: "Tamil", icon: User },
  { value: Genres.Telugu, label: "Telugu", icon: User },
  { value: Genres.Marathi, label: "Marathi", icon: User },
  { value: Genres.Local, label: "Local", icon: MapPin },
  { value: Genres.Classical, label: "Classical", icon: Award },
  { value: Genres.Instrumental, label: "Instrumental", icon: Music },
  { value: Genres.Acapella, label: "Acapella", icon: Mic },
  { value: Genres.LiveOrchestra, label: "Live Orchestra", icon: Award },
  { value: Genres.Karaoke, label: "Karaoke", icon: Mic },
  { value: Genres.SpokenWord, label: "Spoken Word", icon: Speaker },
  { value: Genres.Comedy, label: "Comedy", icon: Smile },
  { value: Genres.Poetry, label: "Poetry", icon: Landmark },
  { value: Genres.Fusion, label: "Fusion", icon: Star },
  { value: Genres.Experimental, label: "Experimental", icon: Cloud },
  { value: Genres.Other, label: "Other", icon: User },
];
